# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: career/v1/activity.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'career/v1/activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from career.v1 import common_pb2 as career_dot_v1_dot_common__pb2
from career.v1 import options_pb2 as career_dot_v1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63\x61reer/v1/activity.proto\x12\tcareer.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x16\x63\x61reer/v1/common.proto\x1a\x17\x63\x61reer/v1/options.proto\"S\n\x13RecordEventsRequest\x12<\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x18.career.v1.ActivityEventB\n\xbaH\x07\x92\x01\x04\x08\x01\x10\x32R\x06\x65vents\"R\n\x14RecordEventsResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05R\x08\x61\x63\x63\x65pted\x12\x1e\n\nduplicates\x18\x02 \x01(\x05R\nduplicates2l\n\x0f\x41\x63tivityService\x12Y\n\x0cRecordEvents\x12\x1e.career.v1.RecordEventsRequest\x1a\x1f.career.v1.RecordEventsResponse\"\x08\x80\xb5\x18\x02\x90\xb5\x18xB\xa7\x01\n\rcom.career.v1B\rActivityProtoP\x01ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\xa2\x02\x03\x43XX\xaa\x02\tCareer.V1\xca\x02\tCareer\\V1\xe2\x02\x15\x43\x61reer\\V1\\GPBMetadata\xea\x02\nCareer::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'career.v1.activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.career.v1B\rActivityProtoP\001ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\242\002\003CXX\252\002\tCareer.V1\312\002\tCareer\\V1\342\002\025Career\\V1\\GPBMetadata\352\002\nCareer::V1'
  _globals['_RECORDEVENTSREQUEST'].fields_by_name['events']._loaded_options = None
  _globals['_RECORDEVENTSREQUEST'].fields_by_name['events']._serialized_options = b'\272H\007\222\001\004\010\001\0202'
  _globals['_ACTIVITYSERVICE'].methods_by_name['RecordEvents']._loaded_options = None
  _globals['_ACTIVITYSERVICE'].methods_by_name['RecordEvents']._serialized_options = b'\200\265\030\002\220\265\030x'
  _globals['_RECORDEVENTSREQUEST']._serialized_start=117
  _globals['_RECORDEVENTSREQUEST']._serialized_end=200
  _globals['_RECORDEVENTSRESPONSE']._serialized_start=202
  _globals['_RECORDEVENTSRESPONSE']._serialized_end=284
  _globals['_ACTIVITYSERVICE']._serialized_start=286
  _globals['_ACTIVITYSERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
