# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: career/v1/download.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'career/v1/download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from career.v1 import options_pb2 as career_dot_v1_dot_options__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63\x61reer/v1/download.proto\x12\tcareer.v1\x1a\x17\x63\x61reer/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x16\n\x14ListDownloadsRequest\"\xd5\x02\n\x0c\x44ownloadItem\x12\x18\n\x07variant\x18\x01 \x01(\tR\x07variant\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07version\x18\x04 \x01(\tR\x07version\x12\x1b\n\ttrack_ids\x18\x05 \x03(\tR\x08trackIds\x12\x1d\n\nsize_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x1b\n\tmime_type\x18\x07 \x01(\tR\x08mimeType\x12\x39\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAt\x12 \n\x0brecommended\x18\t \x01(\x08R\x0brecommended\x12#\n\rdownload_path\x18\n \x01(\tR\x0c\x64ownloadPath\"F\n\x15ListDownloadsResponse\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x17.career.v1.DownloadItemR\x05items2k\n\x0f\x44ownloadService\x12X\n\rListDownloads\x12\x1f.career.v1.ListDownloadsRequest\x1a .career.v1.ListDownloadsResponse\"\x04\x80\xb5\x18\x02\x42\xa7\x01\n\rcom.career.v1B\rDownloadProtoP\x01ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\xa2\x02\x03\x43XX\xaa\x02\tCareer.V1\xca\x02\tCareer\\V1\xe2\x02\x15\x43\x61reer\\V1\\GPBMetadata\xea\x02\nCareer::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'career.v1.download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.career.v1B\rDownloadProtoP\001ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\242\002\003CXX\252\002\tCareer.V1\312\002\tCareer\\V1\342\002\025Career\\V1\\GPBMetadata\352\002\nCareer::V1'
  _globals['_DOWNLOADSERVICE'].methods_by_name['ListDownloads']._loaded_options = None
  _globals['_DOWNLOADSERVICE'].methods_by_name['ListDownloads']._serialized_options = b'\200\265\030\002'
  _globals['_LISTDOWNLOADSREQUEST']._serialized_start=97
  _globals['_LISTDOWNLOADSREQUEST']._serialized_end=119
  _globals['_DOWNLOADITEM']._serialized_start=122
  _globals['_DOWNLOADITEM']._serialized_end=463
  _globals['_LISTDOWNLOADSRESPONSE']._serialized_start=465
  _globals['_LISTDOWNLOADSRESPONSE']._serialized_end=535
  _globals['_DOWNLOADSERVICE']._serialized_start=537
  _globals['_DOWNLOADSERVICE']._serialized_end=644
# @@protoc_insertion_point(module_scope)
