# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: career/v1/events.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'career/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from career.v1 import options_pb2 as career_dot_v1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61reer/v1/events.proto\x12\tcareer.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x17\x63\x61reer/v1/options.proto\"\x84\x02\n\x0c\x42rowserEvent\x12$\n\x08\x65vent_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x08\x18@R\x07\x65ventId\x12\x1d\n\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\x12 \n\x0c\x63lient_ts_ms\x18\x03 \x01(\x03R\nclientTsMs\x12\x1c\n\x04path\x18\x04 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x04R\x04path\x12$\n\x08referrer\x18\x05 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x08R\x08referrer\x12 \n\x07ui_mode\x18\x06 \x01(\tB\x07\xbaH\x04r\x02\x18\x08R\x06uiMode\x12\'\n\nprops_json\x18\x07 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x10R\tpropsJson\"L\n\rRecordRequest\x12;\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.career.v1.BrowserEventB\n\xbaH\x07\x92\x01\x04\x08\x01\x10\x32R\x06\x65vents\",\n\x0eRecordResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05R\x08\x61\x63\x63\x65pted2W\n\x0c\x45ventService\x12G\n\x06Record\x12\x18.career.v1.RecordRequest\x1a\x19.career.v1.RecordResponse\"\x08\x80\xb5\x18\x01\x90\xb5\x18xB\xa5\x01\n\rcom.career.v1B\x0b\x45ventsProtoP\x01ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\xa2\x02\x03\x43XX\xaa\x02\tCareer.V1\xca\x02\tCareer\\V1\xe2\x02\x15\x43\x61reer\\V1\\GPBMetadata\xea\x02\nCareer::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'career.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.career.v1B\013EventsProtoP\001ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\242\002\003CXX\252\002\tCareer.V1\312\002\tCareer\\V1\342\002\025Career\\V1\\GPBMetadata\352\002\nCareer::V1'
  _globals['_BROWSEREVENT'].fields_by_name['event_id']._loaded_options = None
  _globals['_BROWSEREVENT'].fields_by_name['event_id']._serialized_options = b'\272H\006r\004\020\010\030@'
  _globals['_BROWSEREVENT'].fields_by_name['name']._loaded_options = None
  _globals['_BROWSEREVENT'].fields_by_name['name']._serialized_options = b'\272H\006r\004\020\001\030@'
  _globals['_BROWSEREVENT'].fields_by_name['path']._loaded_options = None
  _globals['_BROWSEREVENT'].fields_by_name['path']._serialized_options = b'\272H\005r\003\030\200\004'
  _globals['_BROWSEREVENT'].fields_by_name['referrer']._loaded_options = None
  _globals['_BROWSEREVENT'].fields_by_name['referrer']._serialized_options = b'\272H\005r\003\030\200\010'
  _globals['_BROWSEREVENT'].fields_by_name['ui_mode']._loaded_options = None
  _globals['_BROWSEREVENT'].fields_by_name['ui_mode']._serialized_options = b'\272H\004r\002\030\010'
  _globals['_BROWSEREVENT'].fields_by_name['props_json']._loaded_options = None
  _globals['_BROWSEREVENT'].fields_by_name['props_json']._serialized_options = b'\272H\005r\003\030\200\020'
  _globals['_RECORDREQUEST'].fields_by_name['events']._loaded_options = None
  _globals['_RECORDREQUEST'].fields_by_name['events']._serialized_options = b'\272H\007\222\001\004\010\001\0202'
  _globals['_EVENTSERVICE'].methods_by_name['Record']._loaded_options = None
  _globals['_EVENTSERVICE'].methods_by_name['Record']._serialized_options = b'\200\265\030\001\220\265\030x'
  _globals['_BROWSEREVENT']._serialized_start=92
  _globals['_BROWSEREVENT']._serialized_end=352
  _globals['_RECORDREQUEST']._serialized_start=354
  _globals['_RECORDREQUEST']._serialized_end=430
  _globals['_RECORDRESPONSE']._serialized_start=432
  _globals['_RECORDRESPONSE']._serialized_end=476
  _globals['_EVENTSERVICE']._serialized_start=478
  _globals['_EVENTSERVICE']._serialized_end=565
# @@protoc_insertion_point(module_scope)
