# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: career/v1/options.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'career/v1/options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63\x61reer/v1/options.proto\x12\tcareer.v1\x1a google/protobuf/descriptor.proto*k\n\tAuthLevel\x12\x1a\n\x16\x41UTH_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41UTH_LEVEL_PUBLIC\x10\x01\x12\x15\n\x11\x41UTH_LEVEL_MEMBER\x10\x02\x12\x14\n\x10\x41UTH_LEVEL_ADMIN\x10\x03:J\n\x04\x61uth\x12\x1e.google.protobuf.MethodOptions\x18\xd0\x86\x03 \x01(\x0e\x32\x14.career.v1.AuthLevelR\x04\x61uth:K\n\x10\x61llow_unverified\x12\x1e.google.protobuf.MethodOptions\x18\xd1\x86\x03 \x01(\x08R\x0f\x61llowUnverified:S\n\x15rate_limit_per_minute\x12\x1e.google.protobuf.MethodOptions\x18\xd2\x86\x03 \x01(\rR\x12rateLimitPerMinute:=\n\tmfa_fresh\x12\x1e.google.protobuf.MethodOptions\x18\xd3\x86\x03 \x01(\x08R\x08mfaFreshB\xa6\x01\n\rcom.career.v1B\x0cOptionsProtoP\x01ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\xa2\x02\x03\x43XX\xaa\x02\tCareer.V1\xca\x02\tCareer\\V1\xe2\x02\x15\x43\x61reer\\V1\\GPBMetadata\xea\x02\nCareer::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'career.v1.options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.career.v1B\014OptionsProtoP\001ZBgithub.com/reh3376/career-site/services/api/gen/career/v1;careerv1\242\002\003CXX\252\002\tCareer.V1\312\002\tCareer\\V1\342\002\025Career\\V1\\GPBMetadata\352\002\nCareer::V1'
  _globals['_AUTHLEVEL']._serialized_start=72
  _globals['_AUTHLEVEL']._serialized_end=179
# @@protoc_insertion_point(module_scope)
