# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from career.sidecar.v1 import sidecar_pb2 as career_dot_sidecar_dot_v1_dot_sidecar__pb2


class SidecarServiceStub:
    """Embedding, reranking, classification, and batch jobs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/Embed',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.EmbedRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Rerank = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/Rerank',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RerankRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.Classify = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/Classify',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.RunJob = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/RunJob',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RunJobRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RunJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/GetJob',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GetJobRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/Health',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.HealthRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/Generate',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GenerateRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.RenderResume = channel.unary_unary(
                '/career.sidecar.v1.SidecarService/RenderResume',
                request_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RenderResumeRequest.SerializeToString,
                response_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RenderResumeResponse.FromString,
                _registered_method=True)


class SidecarServiceServicer:
    """Embedding, reranking, classification, and batch jobs.
    """

    def Embed(self, request, context):
        """Embeds one or more texts with the corpus's embedding model. Query and
        document embeddings go through this single implementation so ingest and
        retrieval never diverge. Deadline on the request path: 2 s.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rerank(self, request, context):
        """Re-scores candidate chunks against a query with a cross-encoder and
        returns the top-k. Deadline on the request path: 3 s; on timeout the API
        keeps the hybrid-retrieval order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Classify(self, request, context):
        """Classifies a member message as in scope, out of scope, or a suspected
        prompt injection. Deadline: 1 s; on timeout the API treats the message as
        UNCERTAIN and lets the persona prompt's own scope rules decide.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunJob(self, request, context):
        """Starts a batch job (the same operations as `career-cli`). Returns
        immediately with a job ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Returns a job's status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Reports readiness: models loaded, storage reachable, version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Runs one chat completion with the configured LLM provider (Ollama
        locally / on-host, a hosted API later, stub in CI). Non-streaming;
        the API uses it for background generation (JD-tailored résumés).
        The API owns the prompt text and its version; the sidecar is a
        provider gateway and never rewrites prompts. Deadline is set by the
        caller and can be minutes on CPU inference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderResume(self, request, context):
        """Renders a verified résumé (the API's structured JSON) to a PDF with
        Typst and applies an owner password so the file opens freely but
        cannot be edited. Rendering never touches a model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidecarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.EmbedRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.EmbedResponse.SerializeToString,
            ),
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RerankRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RerankResponse.SerializeToString,
            ),
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.ClassifyRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.ClassifyResponse.SerializeToString,
            ),
            'RunJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RunJob,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RunJobRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RunJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GetJobRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GetJobResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.HealthRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.HealthResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GenerateRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.GenerateResponse.SerializeToString,
            ),
            'RenderResume': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderResume,
                    request_deserializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RenderResumeRequest.FromString,
                    response_serializer=career_dot_sidecar_dot_v1_dot_sidecar__pb2.RenderResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'career.sidecar.v1.SidecarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('career.sidecar.v1.SidecarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidecarService:
    """Embedding, reranking, classification, and batch jobs.
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/Embed',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.EmbedRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/Rerank',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.RerankRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/Classify',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.ClassifyRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/RunJob',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.RunJobRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.RunJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/GetJob',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.GetJobRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/Health',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.HealthRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/Generate',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.GenerateRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career.sidecar.v1.SidecarService/RenderResume',
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.RenderResumeRequest.SerializeToString,
            career_dot_sidecar_dot_v1_dot_sidecar__pb2.RenderResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
